config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'

  get 'home/about'=>'homes#about'
  get 'search' => 'searchs#search'

  resources :users,only: [:show,:index,:edit,:update] do
    member do   #resourcesは7つのルーティングを行ってくれますが、memberを使うことで、別のルーティングを追加できます。
    get :follows, :followers
  end
  resource :relationships, only: [:create, :destroy]
  #resource :relationships, only: [:create, :destroy]
  #get 'followings' => 'relationships#followings', as: 'followings'
  #get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]

    resources :book_comments, only: [:create, :destroy]

  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}



  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
   belongs_to :user
  belongs_to :book


  validates :comment, presence: true


end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

end

app/models/relationship.rb
class Relationship < ApplicationRecord

    belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人


  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人


  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end


  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end



  attachment :profile_image, destroy: false

  validates :name, uniqueness: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)   # =comment = PostComment.new(post_comment_params)comment.user_id = current_user.id
    @book_comment.book_id = @book.id
    if @book_comment.save
    #redirect_to book_path(book)(非同期通信のため)
    else
    render 'books/show'
    end
  end

  def destroy
   @book = Book.find(params[:book_id])
   BookComment.find_by(id: params[:id]).destroy
    #redirect_to book_path(params[:book_id])(非同期通信のため)

  end

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @book_comment = BookComment.new

  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless current_user.id == @book.user_id
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    #redirect_to request.referer(非同期通信のため)

  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    #redirect_to request.referer←元のページに戻るコード（非同期通信のため）

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  # ——————フォロー機能を作成・保存・削除する————————————
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@records = User.search_for(@content, @method)
		else
			@records = Book.search_for(@content, @method)
		end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
   # @following_users = @user.following_user
    #@follower_users = @user.follower_user
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless current_user.id == @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:success] = "You have updated user successfully."
    else
    @books = Book.all
      render :edit
    end
  end


  def follows
    @user = User.find(params[:id])
    @users = @user.followings

  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers

  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_bookcomments.html.erb
     <td>コメント件数：<%= book.book_comments.count %></td>
       <% book.book_comments.each do |book| %>
     <td><%= attachment_image_tag(book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %></td>
     <td><%= book.user.name %></td>
     <td><%= book.comment %></td>

      <% if book.user == current_user %>
     <td><%= link_to "削除", book_book_comment_path(book.book,book), remote: true, method: :delete %></td>
      <% end %>

      <% end %>

app/views/book_comments/_form.html.erb
<%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
<%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
<%= f.submit "送信する" %>
<% end %>

app/views/book_comments/book_comment.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'book_comments/book_comments', book: @book, book_comment: @book_comment) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');

app/views/book_comments/create.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'book_comments/bookcomments', book: @book) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');

app/views/book_comments/destroy.js.erb
<!--id="comments_areaにをrenderで指定した部分テンプレートに更新-->
$("#comments_area").html("<%= j(render 'book_comments/bookcomments', book: @book) %>");
<!--フォームを送信したあとにフォームの値を空にします-->
$("textarea").val('');

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg"%>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>

        <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>

        <td id="favorite_buttons_<%= book.id %>">
　　　    <%= render "favorites/favorite-btn", book: book %>
　　    </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>

   </div>
  </div>
</div>

app/views/books/show.html.erb
<% if @book_comment.errors.any? %>
  <%= @book_comment.errors.count %>件のerrorが発生しました
  <% @book_comment.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user  %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <% if current_user.id == @book.id %>
          <td><%= link_to 'Edit', new_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
           <div id="favorite-btn<%= @book.id %>">
　　　    <%= render "favorites/favorite-btn", book: @book %>
　　      </div>
        </tr>
      </table>
      <div class="new-comment">
        <%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
      </div>
  
      <div id="comments_area">
        <%= render 'book_comments/bookcomments', book: @book %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete,class: "float-left", remote: true do %>
    ♥<%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post,class: "float-left", remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_buttons_<%= @book.id %>").html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$("#favorite_buttons_<%= @book.id %>").html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {book: @book}) %>");

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/searchs/search.html.erb
<% if @model == 'user' %>
	<h3>Users search for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% elsif @model == 'book' %>
	<h3>Books search for "<%= @content %>"</h3>
  <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>

        <td>
          <% if user != current_user %>
          <% if current_user.following?(user) %>
            <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
            <% else %>
            <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class:"btn-sm btn-success" %>
            <% end %>
            <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg" %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to follows_user_path(user) do %>
    <%= user.followings.count %>
    <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to followers_user_path(user) do %>
    <%= user.followers.count %>
    <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
</div>

<% if user != current_user %>
<% if current_user.following?(user) %>
    <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
    <% else %>
    <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST, class:"btn-sm btn-success" %>
<% end %>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <% @user.errors.full_messages.each do |message| %>
  <%= message %>
  <% end %>
<% end %>

<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="cover-user-index">
  <div class="container">
    <div class="row justify-content-center">
      <div>
        <h1 class="font-weight-normal mt-5 mb-5">Follower Users</h1>
          <% if @users.empty? %>
          <div>
            <h1>ユーザーはいません</h1>
          </div>
      </div>
          <% else %>

<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
   </tr>
    <% end %>
  </tbody>
</table>
 <% end %>

  </din>
 </din>
</din>

app/views/users/follows.html.erb
<div class="cover-user-index">
  <div class="container">
    <div class="row justify-content-center">
      <div>
        <h1 class="font-weight-normal mt-5 mb-5">Follower Users</h1>
          <% if @users.empty? %>
          <div>
            <h1>ユーザーはいません</h1>
          </div>
      </div>
          <% else %>

<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
        <td>フォロワー数:<%= user.followers.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
   </tr>
    <% end %>
  </tbody>
</table>
 <% end %>

  </din>
 </din>
</din>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
       <h2>Users</h2>
       <%= render 'index',users: @users %>
    </div>
   </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>